# Generated by Django 5.0.7 on 2024-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_bonus_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='premium_amount',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
