# Generated by Django 5.0.7 on 2024-10-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_sucess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sucess',
            new_name='success',
        ),
    ]
